version: '3.8'

services:
  prod:
    container_name: lendsqr-demo
    image: lendsqr-demo-image
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      bash -c "yarn run start"
    ports:
      - 3010:3010
      - 9229:9229
      - 6379:6379
      - 3306:3306
    networks:
      - lendsqr-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      NODE_ENV: production

networks:
  lendsqr-network:
